server:
  port: 8080

spring:
  application:
    name: MainClient

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet

#  cloud:
#    gateway:
#      routes:
#        - id : broadcast-client-service
#          uri : http://broadcast-client-service
#          predicates :
#            - Path=/broadcast/
#        - id : channel-client-service
#          uri : http://channel-client-service
#          predicates :
#            - Path=/channel/

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

ribbon:
  eureka:
    enabled: false
#  eager-load:
#    enabled: true
#    clients: broadcast-client-service, channel-client-service



#zuul:
#  include-debug-header: true
#  ignored-services: '*'
#  host:
#    max-total-connections: 1000
#    max-per-route-connections: 1000
#  routes:
##    javaexercise:
##      path: /MainClient/**
##      url: forward:/api/mvc/
#
#    broadcast-client-service:
#      ribbon:
#        list-of-servers: localhost:8080
#      path: /broadcast-client-service/**
#      sensitive-headers: null
#      service-id : broadcast-client-service
##      strip-prefix: false
#
#    channel-client-service:
#      ribbon:
#        listOfServers: localhost:8080
#      path: /channel-client-service/**
#      sensitive-headers: null
#      service-id : channel-client-service
##      url : forward:/channel-client-service
##      strip-prefix: false

